dist: trusty

sudo: required

before_script:
  - sudo apt-get update > update.log 2>&1
  - sudo apt-get install --allow-unauthenticated gfortran libblas-dev liblapack-dev python3-pip python3-dev > system_dependencies.log 2>&1
  - sudo pip3 install Cython==0.29 > cython.log 2>&1

script:
  - sudo pip3 install -e .
  - chimaera -h
  - chimaera data/exome_sample_data.txt
  # TODO actual tests
