dist: xenial

sudo: required

before_script:
  - sudo apt-get update
  - sudo -H apt-get install --allow-unauthenticated python3-pip python3-dev gfortran libblas-dev liblapack-dev

script:
  - sudo pip3 install -e .
  - chimaera -h
  - chimaera data/exome_sample_data.txt
  # TODO actual tests
