dist: xenial

python:
  - 3.6

before_script:
  - sudo apt-get update
  - sudo apt-get -H install --allow-unauthenticated gfortran libblas-dev liblapack-dev

script:
  - sudo pip3 install -e .
  - chimaera -h
  - chimaera data/exome_sample_data.txt
  # TODO actual tests
